spring.application.name=QRConnect-Backend

# database config

spring.datasource.url=jdbc:mysql://localhost:3306/qr_connect_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql@2003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt expiration time ---- 7 days
jwt.expiration=604800000